language: csharp

os: linux
dist: trusty
sudo: required

env:
  - ASN1SCC_VERSION="3.3.24"

addons:
  apt:
    sources:
    - sourceline: "ppa:beineri/opt-qt591-trusty"
    packages:
    - qt59base


install:
  - cd $HOME
  - wget https://github.com/n7mobile/3rdparty-deps/releases/download/asn1scc-${ASN1SCC_VERSION}/asn1scc-${ASN1SCC_VERSION}.tar.bz2
  - tar -xvf asn1scc-${ASN1SCC_VERSION}.tar.bz2
  - cd -
  - sudo pip install jsonschema

script:
  - . /opt/qt59/bin/qt59-env.sh
  - PATH=$HOME/asn1scc/:$PATH ./sanity-check.sh
