language: csharp

os: linux
dist: trusty
sudo: required

env:
  global:
    - ASN1SCC_VERSION="3.3.24"
    - CMOCKA_VERSION="1.1.1"

addons:
  apt:
    sources:
    - sourceline: "ppa:beineri/opt-qt591-trusty"
    packages:
    - qt59base

install:
  - pushd $HOME
  - wget https://github.com/n7mobile/3rdparty-deps/releases/download/asn1scc-${ASN1SCC_VERSION}/asn1scc-${ASN1SCC_VERSION}.tar.bz2
  - tar -xvf asn1scc-${ASN1SCC_VERSION}.tar.bz2
  - wget https://cmocka.org/files/1.1/cmocka-${CMOCKA_VERSION}.tar.xz
  - tar -xf cmocka-${CMOCKA_VERSION}.tar.xz
  - cd cmocka-${CMOCKA_VERSION}
  - mkdir build
  - cd build
  - cmake ../
  - make
  - sudo make install
  - popd
  - sudo pip install jsonschema

script:
  - . /opt/qt59/bin/qt59-env.sh
  - PATH=$HOME/asn1scc/:$PATH ./sanity-check.sh
