language: csharp

os: linux
dist: trusty
sudo: required

env:
  global:
    - CMOCKA_VERSION="1.1.1"

addons:
  apt:
    sources:
    - sourceline: "ppa:beineri/opt-qt591-trusty"
    packages:
    - qt59base

install:
  - pushd $HOME
  - wget "https://drive.google.com/uc?export=download&id=1wRwNPbOcIkfZnZOAg2q1k4ZVcKvQiWvK" -O asn1scc.tar.bz2
  - tar -xvf asn1scc.tar.bz2
  - wget https://cmocka.org/files/1.1/cmocka-${CMOCKA_VERSION}.tar.xz
  - tar -xf cmocka-${CMOCKA_VERSION}.tar.xz
  - cd cmocka-${CMOCKA_VERSION}
  - mkdir build
  - cd build
  - cmake ../
  - make
  - sudo make install
  - popd
  - sudo pip install jsonschema

script:
  - . /opt/qt59/bin/qt59-env.sh
  - PATH=$HOME/asn1scc/:$PATH LD_LIBRARY_PATH=/usr/local/lib:$LD_LIBRARY_PATH ./sanity-check.sh
